"""generate_corpus.py — the alien corpora, produced BY φ rather than by hand.

    python3 src/generate_corpus.py beta
    python3 src/generate_corpus.py alpha beta gamma --check-only

Reads Phase 1's three corpora and writes

    conformance/alien.<id>.positive.txt
    conformance/alien.<id>.negative.txt      (annotations preserved verbatim)
    conformance/alien.<id>.vacuous.txt

and, with --winner=<id>, also the unsuffixed
conformance/alien.{positive,negative,vacuous}.txt.

WHY THE NEGATIVE CORPUS IS GENERATED THE SAME WAY
    A negative item does not parse, so it cannot be mapped through the parser —
    it is mapped by the character-level transliterator instead. That is not a
    weakness, it is the test: if a 3DOM NEAR-MISS stops being a near-miss after
    φ, then φ moved something structural and the isomorphism is broken. Gate A3
    asserts every transliterated near-miss still rejects, item by item.

Gates (each mirrors a Phase 1 gate in coverage.py, now per lexicon):

  A1  every alien positive parses to EXACTLY ONE derivation          (G1 / I10)
  A2  the alien positive corpus achieves 100% PRODUCTION COVERAGE     (G2)
  A3  every alien negative is REJECTED                                (G3)
  A4  every alien vacuous item parses and yields ZERO operations      (G4 / D5)
  A5  the L2 differential survives φ: the alien renderings of
      '.car .wheel' and '.car.wheel' parse to DIFFERENT structures    (G5 / I9)
  A6  the Lark front end and the DFA agree on accept/reject for every
      item in all three corpora                                       (G6)
  A7  every alien positive round-trips (φ⁻¹∘φ == id) and its IR content
      hash is IDENTICAL to its 3DOM twin's                            (I1–I10)
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ALIEN = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from canonicalize import content_hash  # noqa: E402
from phi import identity_phi, load_candidate, load_terminals, phase1_dir  # noqa: E402
from transpiler import (ParseError, accepts, dfa_accepts,  # noqa: E402
                        features_with_verbs, lex, num_parses, parse,
                        phi_forward, phi_inverse)
import refgrammar as R                                            # noqa: E402

P1_CONF = os.path.join(phase1_dir(), "conformance")
OUT_DIR = os.path.join(ALIEN, "conformance")
CORPORA = ("positive", "negative", "vacuous")

# Phase 1 header prose that our own header supersedes; dropped rather than
# transliterated so the generated file does not carry two contradictory blurbs.
_SUPERSEDED = (
    "Every line is one", "Every non-comment", "CI asserts", "parses to exactly ONE",
    "ignored by the harness", "Do not edit", "Items are single-line",
    "line) because", "Derived systematically", "yields zero operations",
    "add no production", "raise). They are neither", "ZERO operations",
    "100% production coverage", "each item is preceded", "annotation line:",
    "BOTH grammars", "no production coverage",
)


def read_blocks(path: str, ident) -> list[tuple[str, str]]:
    """[(kind, text)] where kind is 'comment' or 'program'.

    Multi-line-aware for positive/vacuous (Phase 1 ships one deliberately
    pretty-printed multi-line program to exercise clause L1); one program per
    line for negative, which is that file's stated contract — a '#' inside an
    #id selector makes an inline comment delimiter impossible there.
    """
    one_per_line = os.path.basename(path).startswith("negative")
    blocks: list[tuple[str, str]] = []
    buf: list[str] = []
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        stripped = line.strip()
        if not buf and (not stripped or stripped.startswith("#")):
            blocks.append(("comment", line))
            continue
        buf.append(line)
        text = "\n".join(buf)
        if one_per_line or num_parses(text, ident) >= 1:
            blocks.append(("program", text))
            buf = []
    if buf:
        blocks.append(("program", "\n".join(buf)))
    return blocks


HEADERS = {
    "positive": ("POSITIVE conformance corpus", (
        "Every non-comment line is one complete, VALID program in this lexicon.",
        "GENERATED by src/generate_corpus.py from the Phase 1 3DOM corpus by",
        "applying phi — never hand-written. CI asserts each parses to exactly ONE",
        "derivation, that the union achieves 100% production coverage over the same",
        "57 W3C production branches, and that each item's IR content hash equals its",
        "3DOM twin's.")),
    "negative": ("NEGATIVE conformance corpus", (
        "Every non-comment line is exactly ONE invalid program and MUST be rejected.",
        "GENERATED by applying phi to the Phase 1 negative corpus; each item keeps",
        "its VIOLATES/MUTATION annotation verbatim, because production names are",
        "frozen by I1 and so the annotation transfers unchanged. Generating these by",
        "phi is itself an isomorphism check: a 3DOM near-miss that stopped being a",
        "near-miss would mean phi moved something structural.")),
    "vacuous": ("VALID-BUT-VACUOUS corpus (D5)", (
        "Every non-comment line is a SYNTACTICALLY VALID program whose chain has ZERO",
        "operations (a pure query): a PARSE SUCCESS and a TASK FAILURE on any task",
        "whose target IR has >= 1 operation (SCORING_POLICY.md).")),
}


def generate(phi, *, write: bool = True) -> dict[str, list[str]]:
    ident = identity_phi(phi.table)
    produced: dict[str, list[str]] = {}
    for name in CORPORA:
        blocks = read_blocks(os.path.join(P1_CONF, f"{name}.txt"), ident)
        title, blurb = HEADERS[name]
        lines = [f"# alien-syntax/{phi.phi_id} on 3dom-grammar/1.1.0 — {title}"]
        lines += [f"# {b}" for b in blurb]
        lines.append("#")
        programs: list[str] = []
        for kind, text in blocks:
            if kind == "comment":
                body = text.strip()
                if body.startswith("# 3dom-grammar/1.1.0"):
                    continue
                if any(w in text for w in _SUPERSEDED):
                    continue
                lines.append(text)
            else:
                alien = phi_forward(text, phi)
                programs.append(alien)
                lines.append(alien)
        produced[name] = programs
        if write:
            os.makedirs(OUT_DIR, exist_ok=True)
            with open(os.path.join(OUT_DIR, f"alien.{phi.phi_id}.{name}.txt"),
                      "w", encoding="utf-8") as fh:
                fh.write("\n".join(lines) + "\n")
    return produced


def phase1_programs(name: str, ident) -> list[str]:
    return [t for k, t in read_blocks(os.path.join(P1_CONF, f"{name}.txt"), ident)
            if k == "program"]


def check(phi) -> list[str]:
    """Gates A1–A7. Returns the list of failures (empty == PASS)."""
    ident = identity_phi(phi.table)
    fails: list[str] = []
    produced = generate(phi, write=False)
    src = {n: phase1_programs(n, ident) for n in CORPORA}

    for name in CORPORA:
        if len(produced[name]) != len(src[name]):
            fails.append(f"corpus size drift in {name}: {len(produced[name])} "
                         f"vs Phase 1 {len(src[name])}")

    bad = [p for p in produced["positive"] if num_parses(p, phi) != 1]
    if bad:
        fails.append(f"A1: {len(bad)} positive(s) not uniquely parsing, "
                     f"first {bad[0][:60]!r}")

    covered: set[str] = set()
    for p in produced["positive"]:
        if num_parses(p, phi) == 1:
            covered |= features_with_verbs(p, phi)
    missing = R.all_features() - covered
    if missing:
        fails.append(f"A2: {len(missing)} uncovered branch(es): "
                     f"{', '.join(sorted(missing)[:6])}")

    accepted = [p for p in produced["negative"] if num_parses(p, phi) != 0]
    if accepted:
        fails.append(f"A3: {len(accepted)} negative(s) accepted, "
                     f"first {accepted[0][:60]!r}")

    vbad = [p for p in produced["vacuous"]
            if num_parses(p, phi) != 1
            or sum(1 for t in lex(p, phi) if t[0] == "VERB") != 0]
    if vbad:
        fails.append(f"A4: {len(vbad)} vacuous item(s) invalid, "
                     f"first {vbad[0][:60]!r}")

    a = phi_forward("(function(){ $S('.car .wheel').delete(); })();", phi)
    b = phi_forward("(function(){ $S('.car.wheel').delete(); })();", phi)
    fa, _ = R.derive(lex(a, phi))
    fb, _ = R.derive(lex(b, phi))
    if not (("combinator", 0) in fa and ("matchers", 1) in fb and fa != fb):
        fails.append("A5: the descendant/compound differential did not survive φ")

    disagree = [(n, p) for n in CORPORA for p in produced[n]
                if accepts(p, phi) != dfa_accepts(p, phi)]
    if disagree:
        fails.append(f"A6: {len(disagree)} Earley/DFA disagreement(s), "
                     f"first {disagree[0][1][:60]!r}")

    for original, alien in zip(src["positive"], produced["positive"]):
        if phi_inverse(alien, phi) != original:
            fails.append(f"A7: φ⁻¹∘φ != id on {original[:50]!r}")
            break
        try:
            if content_hash(parse(alien, phi)) != content_hash(parse(original, ident)):
                fails.append(f"A7: IR differs for {original[:50]!r}")
                break
        except ParseError as exc:
            fails.append(f"A7: {original[:40]!r} failed to parse: {exc}")
            break
    return fails


def main(argv: list[str]) -> int:
    names = [a for a in argv[1:] if not a.startswith("-")] or ["alpha", "beta", "gamma"]
    check_only = "--check-only" in argv
    winner = next((a.split("=", 1)[1] for a in argv[1:]
                   if a.startswith("--winner=")), None)
    load_terminals()
    status = 0
    for name in names:
        phi = load_candidate(name)
        fails = check(phi)
        if not check_only:
            generate(phi)
        print(f"φ = {name:<8} A1–A7 {'PASS' if not fails else 'FAIL'}")
        for f in fails:
            print(f"    - {f}")
            status = 1
        if winner == name and not fails and not check_only:
            for corpus in CORPORA:
                with open(os.path.join(OUT_DIR, f"alien.{name}.{corpus}.txt"),
                          encoding="utf-8") as fh:
                    body = fh.read()
                with open(os.path.join(OUT_DIR, f"alien.{corpus}.txt"),
                          "w", encoding="utf-8") as fh:
                    fh.write(body)
                print(f"    winner -> alien.{corpus}.txt")
    return status


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
