"""metrics_parity.py — regenerate reports/METRICS_PARITY.md from the artifacts.

    python3 measure/metrics_parity.py > reports/METRICS_PARITY.md

Phase 1's METRICS.md carries the instruction "Generated by grammar_metrics.py.
Do not hand-edit." The parity table inherits that rule: it is computed from the
GENERATED .ebnf files, the shared DFA and the parallel corpora, so it cannot
drift away from the grammars it describes.

INVARIANT rows must match 3DOM exactly and are reported PASS/FAIL.
REPORTED rows are measurements; a difference there is a finding, not a failure.
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ALIEN = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ALIEN, "src"))
sys.path.insert(0, HERE)

from phi import identity_phi, load_candidate, phase1_dir  # noqa: E402
from transpiler import lex, num_parses  # noqa: E402
import collisions as C  # noqa: E402
import dfa_parity as D  # noqa: E402
import fertility as F  # noqa: E402
import generate_corpus as G  # noqa: E402
import refgrammar as R  # noqa: E402

sys.path.insert(0, phase1_dir())
import grammar_metrics as GM  # noqa: E402

GENERATED = os.path.join(ALIEN, "grammar", "generated")
CANDIDATES = ("alpha", "beta", "gamma")


def rule_shapes(path: str) -> dict[str, tuple[int, int]]:
    """{rule: (max alternation branching, max RHS length in symbols)} from W3C."""
    body = GM.strip_comments(open(path, encoding="utf-8").read(), "w3c")
    parts = re.split(r"\n(?=[A-Za-z_][A-Za-z0-9_]*\s*::=)", body)
    rx = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*::=(.*)$", re.S)
    out: dict[str, tuple[int, int]] = {}
    for part in parts:
        m = rx.match(part)
        if not m:
            continue
        name, rhs = m.group(1), m.group(2)
        # blank quoted literals so a literal '|' inside one cannot fool the split
        masked = re.sub(r"'[^']*'|\"[^\"]*\"", " LIT ", rhs)
        alts = masked.split("|")
        out[name] = (len(alts), max(len(a.split()) for a in alts))
    return out


def grammar_row(name: str) -> dict[str, object]:
    if name == "identity":
        w3c = os.path.join(phase1_dir(), "3dom_grammar.w3c.ebnf")
        iso = os.path.join(phase1_dir(), "3dom_grammar.iso.ebnf")
    else:
        w3c = os.path.join(GENERATED, f"alien.{name}.w3c.ebnf")
        iso = os.path.join(GENERATED, f"alien.{name}.iso.ebnf")
    mw, mi = GM.parse_ebnf(w3c, "w3c"), GM.parse_ebnf(iso, "iso")
    shapes = rule_shapes(w3c)
    phi = load_candidate(name)
    stats = D.branching_stats()
    programs = (G.phase1_programs("positive", identity_phi())
                if name == "identity"
                else G.generate(phi, write=False)["positive"])
    roles: dict[str, int] = {}
    for t in phi.table.terminals:
        roles[t.role] = roles.get(t.role, 0) + 1
    unambiguous = all(num_parses(p, phi) == 1 for p in programs)
    structural = F.structural_row(name)
    return {
        "|N|": mw["N"],
        "|P| (W3C)": mw["P"],
        "|P| (ISO)": mi["P"],
        "|Σq| distinct quoted SPELLINGS": len({q for q in mw["quoted"]
                                               if q not in ("", "LIT", "SPECIAL")}),
        "distinct terminal ROLES": len(phi.table.terminals),
        "declared collision groups preserved":
            "yes" if not C.check_c_overload(phi, identity_phi(phi.table)) else "NO",
        "max alternation branching": max(a for a, _ in shapes.values()),
        "max RHS length": max(b for _, b in shapes.values()),
        "EBNF `*` (0+)": mw["ops"]["*"],
        "EBNF `+` (1+)": mw["ops"]["+"],
        "EBNF `?` (opt)": mw["ops"]["?"],
        "closed verb set": roles["operation verb"],
        "type_selector set": roles["type selector keyword"],
        "pseudo_selector set": roles["pseudo-selector keyword"],
        "argument kinds": len(GM.strip_comments(
            open(w3c, encoding="utf-8").read(), "w3c").split("argument           ::=")[1]
            .split("\n")[0].split("|")),
        "Chomsky class": "Regular",
        "unambiguous over positives": "yes" if unambiguous else "NO",
        "lookahead k": 2,
        "DFA states": int(stats["states"]),
        "mean DFA branching": round(stats["mean_branching"], 3),
        "max DFA branching": int(stats["max_branching"]),
        "chars per program": round(structural["chars/program"], 3),
        "UTF-8 bytes per program": round(structural["utf8 bytes/program"], 3),
        "bytes per char": round(structural["bytes/char"], 3),
        "DSL tokens per program": round(
            sum(len(lex(p, phi)) for p in programs) / len(programs), 3),
    }


INVARIANT_ROWS = (
    "|N|", "|P| (W3C)", "|P| (ISO)",
    "distinct terminal ROLES", "declared collision groups preserved",
    "max alternation branching", "max RHS length",
    "EBNF `*` (0+)", "EBNF `+` (1+)", "EBNF `?` (opt)",
    "closed verb set", "type_selector set", "pseudo_selector set",
    "argument kinds", "Chomsky class", "unambiguous over positives",
    "lookahead k", "mean DFA branching", "max DFA branching",
)
# |Σq| is reported SEPARATELY, below the table, with its diagnosis. It is the
# one row that does not pass, and it does not pass for a reason about the
# METRIC's definition rather than about any candidate — see the repair note.
SPELLING_ROW = "|Σq| distinct quoted SPELLINGS"

REPORTED_ROWS = (
    "DFA states", "chars per program", "UTF-8 bytes per program",
    "bytes per char", "DSL tokens per program",
)


def main() -> int:
    rows = {n: grammar_row(n) for n in ("identity",) + CANDIDATES}
    base = rows["identity"]
    names = ("identity",) + CANDIDATES

    print("# METRICS_PARITY.md — matched complexity, 3DOM vs each alien lexicon\n")
    print("**grammar version:** `3dom-grammar/1.1.0`\n")
    print("_Generated by `measure/metrics_parity.py` from the GENERATED `.ebnf` "
          "files, the shared DFA and the parallel corpora. Do not hand-edit._ "
          "`identity` is 3DOM itself, expressed as the φ = id member of the "
          "family, so the baseline column is produced by the same code path as "
          "the others.\n")

    print("## INVARIANT rows — must match exactly\n")
    print("| Metric | " + " | ".join(f"`{n}`" for n in names) + " | Verdict |")
    print("|---" * (len(names) + 2) + "|")
    failures = 0
    for metric in INVARIANT_ROWS:
        cells = [str(rows[n][metric]) for n in names]
        ok = all(rows[n][metric] == base[metric] for n in names)
        failures += 0 if ok else 1
        print(f"| {metric} | " + " | ".join(cells)
              + f" | {'**PASS**' if ok else '**FAIL**'} |")

    print(f"\n**{len(INVARIANT_ROWS) - failures} / {len(INVARIANT_ROWS)} INVARIANT "
          f"rows PASS for every candidate.**\n")

    # ── the one row that does not pass, and why ─────────────────────────────
    sp = {n: rows[n][SPELLING_ROW] for n in names}
    print("## The one row that does NOT match, and the Phase 1 repair it implies\n")
    print("| Metric | " + " | ".join(f"`{n}`" for n in names) + " | Verdict |")
    print("|---" * (len(names) + 2) + "|")
    same = all(v == sp["identity"] for v in sp.values())
    print(f"| {SPELLING_ROW} | " + " | ".join(str(sp[n]) for n in names)
          + f" | {'**PASS**' if same else '**FAIL**'} |")
    print(f"""
**Diagnosis.** METRICS.md marks `|Σq|` INVARIANT, but `|Σq|` counts distinct
quoted **SPELLINGS**, while the isomorphism contract fixes terminal **ROLES**.
In 3DOM the character `.` occupies **three** grammar sites:

    operation_call ::= '.' verb '(' argument_list? ')'     the chain operator
    class_selector ::= '.' identifier                      the class sigil
    number         ::= sign? digit+ ( '.' digit+ )?        the DECIMAL POINT

Content-keyed counting collapses all three into one entry, which is where 39
comes from. `terminals.json`'s `collisions` block declares only the first two
(`T_CHAIN_OP` vs `T_CLASS_SIGIL`); the decimal point is part of the value class
`T_NUMBER`, which is `substitutable:false` because its values are copied verbatim
into the shared IR.

So any φ that renames the chain operator and the class sigil — which it MUST, or
the CSS/jQuery prior survives untouched — while leaving the decimal point alone —
which it MUST, because `T_NUMBER` is frozen — necessarily separates a spelling
3DOM happened to share, and `|Σq|` goes 39 → 40. There is no φ that satisfies
both obligations and holds this row.

`alpha` holds it at 39 by COINCIDENCE, not by design: its derangement sends the
wildcard `*` → `.` and the chain/class pair `.` → `#`, so `.` re-enters the
inventory from a different role and the cardinality happens to survive. Reading
that column as a pass would be reading luck as evidence.

**What this row is NOT.** It is not a structural difference. `|N|`, `|P|`, the
operator skeleton, the max alternation branching, the max RHS length, the Chomsky
class, unambiguity, `k`, every closed-set size, and both DFA branching figures all
match exactly, in both notations, for all three candidates. Nothing about the
DECODER's problem differs: the DSL token alphabet, every token stream over the
parallel corpus, and the position-indexed branching profile are identical
(`measure/dfa_parity.py`, tolerance 0.000).

**The repair, which is Phase 1's to make and is NOT made here.** Two options:

1. *Re-define the row* as **distinct terminal ROLES** (43, from `terminals.json`),
   which is what the matched-complexity claim actually needs and which passes for
   every candidate. This is the recommended option: the role count is the quantity
   the isomorphism contract fixes, and it is already machine-checkable.
2. *Demote `|Σq|` to REPORTED*, and add the decimal point to `terminals.json`'s
   `collisions` block as a third, undeclared `.` overload — so that the coincidence
   is documented rather than silently load-bearing.

Either way `terminals.json`'s `collisions` block should gain the `.`-as-decimal-
point entry: it currently documents two of the three roles that character plays.
**No change to the 3DOM grammar is required, and none has been made** — this is a
metric-definition and metadata repair, and Phase 2 does not touch Phase 1.
""")

    print("## REPORTED rows — measurements, not constraints\n")
    print("| Metric | " + " | ".join(f"`{n}`" for n in names) + " |")
    print("|---" * (len(names) + 1) + "|")
    for metric in REPORTED_ROWS:
        print(f"| {metric} | " + " | ".join(str(rows[n][metric]) for n in names)
              + " |")

    print("\n### Lexical hazard checks (`measure/collisions.py`)\n")
    print("| lexicon | checks (a)–(f) — CONSTRAINT 2 | check (g) — proposed |")
    print("|---|---|---|")
    for n in names:
        spec, prop = C.run(load_candidate(n))
        ns, np_ = sum(len(v) for v in spec.values()), sum(len(v) for v in prop.values())
        print(f"| `{n}` | {'**PASS** (0)' if not ns else f'**FAIL** ({ns})'} | "
              f"{'**PASS** (0)' if not np_ else f'**FAIL** ({np_})'} |")

    print("\n### DFA branching parity (`measure/dfa_parity.py`)\n")
    print("| lexicon | token-alphabet parity | token-stream parity | "
          "positional-profile parity |")
    print("|---|---|---|---|")
    for n in names:
        res = D.compare(load_candidate(n))
        f = res["fails"]
        def cell(tag: str) -> str:
            return "**FAIL**" if any(x.startswith(tag) for x in f) else "**PASS**"
        print(f"| `{n}` | {cell('P1')} | {cell('P2')} | {cell('P4')} |")

    print("\n### Rows that are still UNMEASURED\n")
    print("| Row | Why | How to fill it |")
    print("|---|---|---|")
    print("| tokens per program, per tokenizer | needs `transformers` and the "
          "five study tokenizers | `python3 measure/fertility.py --md` |")
    print("| fertility ratio (tokens ÷ chars) | same | same; this row is "
          "CONSTRAINT 1 of the selection rule |")
    print("| ΔNLL per token / per character | needs `torch` + the four "
          "Qwen2.5-Coder BASE checkpoints | `python3 measure/prior_strength.py --md` |")
    print("\nUntil those three rows exist, the winner in "
          "`reports/CANDIDATE_SELECTION.md` is PROVISIONAL, and it says so.\n")

    print("## The generated alien grammar is still REGULAR\n")
    print("""A CFG is **non-self-embedding** iff no non-terminal `A` admits a
derivation `A ⇒* α A β` with `α ≠ ε` **and** `β ≠ ε`; such a grammar generates a
regular language (Chomsky 1959). Phase 1 gives that argument for 3DOM by
enumerating its only recursive non-terminals — `stmts`, `ops`, `argtail`,
`ctail`, `matchers` — and observing that every one is RIGHT-recursive, so β = ε.

The argument transfers without redoing it, and the reason is the isomorphism
contract rather than a re-inspection. φ is a bijection on Σ that leaves N and the
shape of P fixed (I1–I3): for every production `A → X₁…Xₖ` of P_3DOM, P_alien
contains `φ(A) → φ(X₁)…φ(Xₖ)` with the same length, the same symbol POSITIONS,
and the same operator skeleton. Self-embedding is a property of where
NON-TERMINALS sit in a right-hand side, and φ is the identity on non-terminals
(I1) and moves no symbol from one position to another (I3). So `A ⇒* α A β` holds
in the alien grammar exactly when it holds in 3DOM. It holds nowhere in 3DOM;
therefore it holds nowhere in the alien grammar, which is therefore
non-self-embedding and regular.

This is checked as well as argued: `tests/test_invariants.py::test_I4_regular_
non_self_embedding` exhibits the 52-state DFA and shows it accepts every alien
positive item. A finite automaton accepting the language exists **iff** the
language is regular.
""")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
